#!/usr/bin/env bash
#
# cli/mcp.sh - MCP Docker Services Management
# Handles all MCP (Model Context Protocol) Docker container operations
#

# Source common utilities if not already loaded
[[ -z "${_COMMON_LOADED:-}" ]] && source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

# ============================================
# MCP Services List (explicitly defined to avoid building prod services)
# ============================================
MCP_SERVICES="mcp-gateway mcp-filesystem mcp-websearch mcp-github mcp-python mcp-database mcp-memory"

# ============================================
# MCP Workspace Setup
# ============================================

setup_mcp_workspace() {
    echo
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${CYAN}  Setting up MCP Workspace${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo
    
    use_docker_compose
    
    # Step 1: Create shared workspace for MCP filesystem service
    echo -e "  ${BLUE}[1/3]${NC} Creating shared workspace directory..."
    mkdir -p shared-workspace
    echo -e "        ${GREEN}✓${NC} shared-workspace/"
    
    # Step 2: Create data directories (for local bind mounts if needed)
    echo -e "  ${BLUE}[2/3]${NC} Creating data directories..."
    mkdir -p data
    echo -e "        ${GREEN}✓${NC} data/"
    
    # Step 3: Handle SELinux contexts if enabled
    echo -e "  ${BLUE}[3/3]${NC} Checking SELinux..."
    if is_selinux_enabled; then
        echo -e "        ${YELLOW}!${NC} SELinux detected ($(getenforce))"
        echo -e "        Setting container contexts..."
        set_selinux_context "shared-workspace"
        echo -e "        ${GREEN}✓${NC} shared-workspace context set"
        set_selinux_context "data"
        echo -e "        ${GREEN}✓${NC} data context set"
    else
        echo -e "        ${CYAN}○${NC} SELinux not enforcing (skipped)"
    fi
    
    # Note: Observability services now use Docker named volumes
    # which handle permissions automatically
    
    cd "$SCRIPT_DIR"
    echo
    log_success "MCP workspace ready"
}

setup_mcp_env() {
    use_docker_compose
    
    if [[ ! -f ".env" ]] && [[ -f ".env.template" ]]; then
        cp ".env.template" ".env"
        log_success "Created MCP .env from template"
    elif [[ ! -f ".env" ]]; then
        cat > ".env" << 'EOF'
# MCP Docker Configuration
# Generated by magentic.sh

# GitHub Token (optional, for increased API rate limits)
GITHUB_TOKEN=

# Gateway Configuration
LOG_LEVEL=INFO
HEALTH_CHECK_INTERVAL=60
REQUEST_TIMEOUT=30
MAX_RETRIES=3
ENABLE_METRICS=true

# Database Configuration
ALLOW_WRITE_OPS=true

# Python Execution Configuration
MAX_EXECUTION_TIME=30
MAX_MEMORY_MB=256

# Memory Store Configuration
DEFAULT_TTL=3600
MAX_KEYS_PER_NAMESPACE=10000
EOF
        log_success "Created default MCP .env file"
    fi
    
    cd "$SCRIPT_DIR"
}

# ============================================
# MCP Service Management
# ============================================

mcp_start() {
    if ! check_docker; then
        log_warning "Skipping MCP services (Docker not available)"
        return 1
    fi
    
    echo
    echo -e "${MAGENTA}╔═══════════════════════════════════════════════════════╗${NC}"
    echo -e "${MAGENTA}║           Starting MCP Services                       ║${NC}"
    echo -e "${MAGENTA}╚═══════════════════════════════════════════════════════╝${NC}"
    
    use_docker_compose
    local compose_cmd=$(get_compose_cmd)
    
    # Step 1: Setup environment
    echo
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${CYAN}  Step 1: Environment Setup${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    setup_mcp_env
    log_success "Environment configured"
    
    # Step 2: Setup workspace
    setup_mcp_workspace
    
    # Step 3: Build Docker images (MCP services only)
    echo
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${CYAN}  Step 2: Building MCP Docker Images${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo
    
    # Explicitly list MCP services (these are the ones without profiles or with no profile restriction)
    # This avoids building magentic-backend and magentic-frontend which have profiles: ["prod", "app"]
    local total_services=$(echo "$MCP_SERVICES" | wc -w)
    
    echo -e "  ${BLUE}Building $total_services MCP services...${NC}"
    for svc in $MCP_SERVICES; do
        echo -e "    • $svc"
    done
    echo
    
    # Build only MCP services explicitly (not prod/app profile services)
    if [[ -t 1 ]]; then
        # Interactive terminal - show progress
        $compose_cmd build $MCP_SERVICES 2>&1 | while IFS= read -r line; do
            # Filter and format build output
            if [[ "$line" =~ ^\[\+\].*Building ]]; then
                echo -e "  ${YELLOW}▶${NC} $line"
            elif [[ "$line" =~ "Successfully built" ]] || [[ "$line" =~ "Built" ]]; then
                echo -e "  ${GREEN}✓${NC} $line"
            elif [[ "$line" =~ "#"[0-9]+" " ]]; then
                # Buildkit progress line
                printf "\r  ${BLUE}⋯${NC} %.70s" "$line"
            elif [[ "$line" =~ "error" ]] || [[ "$line" =~ "Error" ]]; then
                echo -e "\n  ${RED}✗${NC} $line"
            fi
        done
        echo  # Clear line
    else
        # Non-interactive - build quietly
        $compose_cmd build --quiet $MCP_SERVICES
    fi
    
    log_success "MCP Docker images built"
    
    # Step 4: Start MCP containers only
    echo
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${CYAN}  Step 3: Starting MCP Containers${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo
    
    $compose_cmd up -d $MCP_SERVICES 2>&1 | while IFS= read -r line; do
        if [[ -n "$line" ]]; then
            if [[ "$line" =~ "Started" ]] || [[ "$line" =~ "Running" ]]; then
                echo -e "  ${GREEN}✓${NC} $line"
            elif [[ "$line" =~ "Creating" ]] || [[ "$line" =~ "Starting" ]]; then
                echo -e "  ${BLUE}▶${NC} $line"
            else
                echo -e "  ${CYAN}○${NC} $line"
            fi
        fi
    done
    
    # Show container status (MCP only)
    echo
    echo -e "  ${BLUE}Container Status:${NC}"
    $compose_cmd ps --format "table {{.Name}}\t{{.Status}}" 2>/dev/null | grep -E '(NAME|mcp-)' | head -10 | while IFS= read -r line; do
        if [[ "$line" =~ "Up" ]] || [[ "$line" =~ "running" ]]; then
            echo -e "    ${GREEN}●${NC} $line"
        elif [[ "$line" =~ "NAME" ]]; then
            echo -e "    $line"
        else
            echo -e "    ${YELLOW}○${NC} $line"
        fi
    done
    
    # Step 5: Wait for gateway
    echo
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${CYAN}  Step 4: Waiting for MCP Gateway${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo
    
    local max_attempts=30
    local attempt=0
    
    while [[ $attempt -lt $max_attempts ]]; do
        if curl -sf "http://localhost:$MCP_GATEWAY_PORT/health" > /dev/null 2>&1; then
            echo -e "\r  ${GREEN}✓${NC} MCP Gateway responding                    "
            break
        fi
        ((attempt++))
        local progress=$((attempt * 100 / max_attempts))
        local bar_width=30
        local filled=$((progress * bar_width / 100))
        local empty=$((bar_width - filled))
        printf "\r  ${BLUE}⋯${NC} Waiting... [${GREEN}%s${NC}%s] %d/%ds" \
            "$(printf '#%.0s' $(seq 1 $filled 2>/dev/null) 2>/dev/null)" \
            "$(printf '.%.0s' $(seq 1 $empty 2>/dev/null) 2>/dev/null)" \
            "$attempt" "$max_attempts"
        sleep 1
    done
    
    echo
    
    if [[ $attempt -ge $max_attempts ]]; then
        log_error "MCP Gateway failed to start within ${max_attempts}s"
        echo
        echo -e "  ${YELLOW}Recent logs:${NC}"
        $compose_cmd logs --tail=15 mcp-gateway 2>&1 | head -20 | sed 's/^/    /'
        cd "$SCRIPT_DIR"
        return 1
    fi
    
    # Show health status
    local health=$(curl -sf "http://localhost:$MCP_GATEWAY_PORT/health" 2>/dev/null)
    if [[ -n "$health" ]]; then
        local healthy=$(echo "$health" | grep -o '"healthy_servers":[0-9]*' | cut -d: -f2)
        local total=$(echo "$health" | grep -o '"total_servers":[0-9]*' | cut -d: -f2)
        echo -e "  ${GREEN}✓${NC} MCP Servers: ${GREEN}$healthy${NC}/$total healthy"
    fi
    
    echo
    echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    log_success "MCP Services started successfully!"
    echo -e "  Gateway: ${CYAN}http://localhost:$MCP_GATEWAY_PORT${NC}"
    echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    
    cd "$SCRIPT_DIR"
    return 0
}

mcp_stop() {
    if ! check_docker_silent; then
        return 0
    fi
    
    log_info "Stopping MCP services..."
    
    use_docker_compose
    local compose_cmd=$(get_compose_cmd)
    
    # Only stop MCP services (using explicit list)
    $compose_cmd stop $MCP_SERVICES 2>/dev/null || true
    $compose_cmd rm -f $MCP_SERVICES 2>/dev/null || true
    
    cd "$SCRIPT_DIR"
    
    log_success "MCP services stopped"
}

mcp_restart() {
    log_info "Restarting MCP services..."
    mcp_stop
    sleep 2
    mcp_start
}

mcp_remove() {
    if ! check_docker; then
        return 0
    fi
    
    log_warning "This will remove MCP containers, volumes, and data!"
    read -p "Are you sure? (y/N): " -n 1 -r
    echo
    
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        use_docker_compose
        local compose_cmd=$(get_compose_cmd)
        
        # Only remove MCP services (using explicit list)
        $compose_cmd stop $MCP_SERVICES 2>/dev/null || true
        $compose_cmd rm -f -v $MCP_SERVICES 2>/dev/null || true
        
        # Remove MCP-specific data (not backend data)
        if [[ -d "data/memory" ]]; then
            rm -rf data/memory/*
            log_success "MCP memory data cleared"
        fi
        
        cd "$SCRIPT_DIR"
        log_success "MCP resources removed"
    else
        log_info "Cancelled"
    fi
}

mcp_status() {
    echo
    echo -e "${CYAN}═══════════════════════════════════════════════════${NC}"
    echo -e "${CYAN}                  MCP Service Status               ${NC}"
    echo -e "${CYAN}═══════════════════════════════════════════════════${NC}"
    echo
    
    if ! check_docker_silent; then
        echo -e "  ${RED}Docker not available${NC}"
        return 1
    fi
    
    use_docker_compose
    local compose_cmd=$(get_compose_cmd)
    
    # Show MCP container status only
    echo -e "${BLUE}MCP Container Status:${NC}"
    $compose_cmd ps --format "table {{.Name}}\t{{.Status}}\t{{.Ports}}" 2>/dev/null | grep -E '(NAME|mcp-)' || \
        $compose_cmd ps 2>/dev/null | grep -E '(NAME|mcp-)'
    echo
    
    # Gateway health
    if is_mcp_running; then
        echo -e "${BLUE}Gateway Health:${NC}"
        local health=$(curl -sf "http://localhost:$MCP_GATEWAY_PORT/health" 2>/dev/null)
        if [[ -n "$health" ]]; then
            echo "$health" | python3 -m json.tool 2>/dev/null || echo "$health"
        fi
        
        echo
        echo -e "${BLUE}Available Tools:${NC}"
        local tools=$(curl -sf "http://localhost:$MCP_GATEWAY_PORT/tools" 2>/dev/null)
        if [[ -n "$tools" ]]; then
            echo "$tools" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    print(f\"  Total: {data.get('total_tools', 'N/A')} tools\")
    for server, count in data.get('by_server', {}).items():
        print(f\"    • {server}: {count} tools\")
except: pass
" 2>/dev/null
        fi
    else
        echo -e "  ${YELLOW}Gateway not responding${NC}"
    fi
    
    echo
    echo -e "${GREEN}Endpoints:${NC}"
    echo "  • Gateway:  http://localhost:$MCP_GATEWAY_PORT"
    echo "  • Health:   http://localhost:$MCP_GATEWAY_PORT/health"
    echo "  • Tools:    http://localhost:$MCP_GATEWAY_PORT/tools"
    echo "  • Metrics:  http://localhost:$MCP_GATEWAY_PORT/metrics"
    echo
    
    cd "$SCRIPT_DIR"
}

mcp_logs() {
    if ! check_docker_silent; then
        log_error "Docker not available"
        return 1
    fi
    
    local service=${1:-}
    use_docker_compose
    local compose_cmd=$(get_compose_cmd)
    
    if [[ -n "$service" ]]; then
        log_info "Showing logs for $service..."
        $compose_cmd logs -f --tail=100 "$service"
    else
        # Show logs for MCP services only (using explicit list)
        log_info "Showing logs for MCP services..."
        $compose_cmd logs -f --tail=100 $MCP_SERVICES
    fi
    
    cd "$SCRIPT_DIR"
}

mcp_build() {
    if ! check_docker; then
        log_error "Docker not available"
        return 1
    fi
    
    echo
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${CYAN}  Building MCP Docker Images${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo
    
    use_docker_compose
    local compose_cmd=$(get_compose_cmd)
    
    # Using explicit MCP services list
    echo -e "  ${BLUE}MCP services to build:${NC}"
    for svc in $MCP_SERVICES; do
        echo -e "    • $svc"
    done
    echo
    
    # Build with progress
    log_info "Building (this may take a while)..."
    echo
    
    if [[ "$*" =~ "--quiet" ]] || [[ "$*" =~ "-q" ]]; then
        $compose_cmd build --quiet $MCP_SERVICES
    else
        $compose_cmd build --progress=plain $MCP_SERVICES 2>&1 | while IFS= read -r line; do
            if [[ "$line" =~ "#"[0-9]+" DONE" ]]; then
                echo -e "  ${GREEN}✓${NC} $line"
            elif [[ "$line" =~ "#"[0-9]+" " ]]; then
                echo -e "  ${BLUE}▶${NC} $line"
            elif [[ "$line" =~ "error" ]] || [[ "$line" =~ "Error" ]]; then
                echo -e "  ${RED}✗${NC} $line"
            fi
        done
    fi
    
    echo
    cd "$SCRIPT_DIR"
    log_success "MCP images built"
}

# ============================================
# Command Handler
# ============================================

handle_mcp_command() {
    local command=${1:-}
    shift 2>/dev/null || true
    
    case $command in
        mcp)
            mcp_start
            ;;
        mcp-start)
            mcp_start
            ;;
        mcp-stop)
            mcp_stop
            ;;
        mcp-restart)
            mcp_restart
            ;;
        mcp-status)
            mcp_status
            ;;
        mcp-logs)
            mcp_logs "$@"
            ;;
        mcp-build)
            mcp_build "$@"
            ;;
        mcp-remove)
            mcp_remove
            ;;
        *)
            log_error "Unknown MCP command: $command"
            echo "Available: mcp, mcp-stop, mcp-restart, mcp-status, mcp-logs, mcp-build, mcp-remove"
            return 1
            ;;
    esac
}
